CREATE TABLE BCA_TRANSACOES(
	TRA_COD INT IDENTITY(1,1) PRIMARY KEY,
	TRA_NUM_CARTAO VARCHAR(20) NOT NULL,
	TRA_VALOR DECIMAL(10,2) NOT NULL,
	TRA_DATA DATETIME NOT NULL,
	TRA_DESCRICAO VARCHAR(255)	

)

CREATE TABLE BCA_CLIENTES(
	CLI_COD INT IDENTITY(1,1) PRIMARY KEY,
	CLI_NOME VARCHAR(100) NOT NULL,
	CLI_NUM_CARTAO VARCHAR(20) UNIQUE NOT NULL
)

CREATE INDEX IX_TRA_NUMCARTAO ON BCA_TRANSACOES(TRA_NUM_CARTAO)
CREATE INDEX IX_TRA_DATA ON BCA_TRANSACOES(TRA_DATA)

ALTER TABLE BCA_TRANSACOES ADD CONSTRAINT FK_TRANSACOES_CLIENTES FOREIGN KEY (TRA_NUM_CARTAO) REFERENCES BCA_CLIENTES(CLI_NUM_CARTAO)